### ISSUE TITLE
能否提供编译好的文件

### ISSUE THREAD

**Issue by ii2day** [W-Mai/BuZhiYin#21]
对于不懂的swift的人来说，好像用起来不太会用。

**Comment by ii2day** [comment]
sorry 没看到  app store里面有

**Comment by W-Mai** [comment]
你好，您的提问非常的好，对于不懂swift的人来说，没有二进制文件使用起来非常的麻烦。

介于此，我们已经上架到App Store中了，欢迎下载，欢迎star本项目

感谢！

**Comment by W-Mai** [comment]
> sorry 没看到 app store里面有

你好，欢迎加入README中的讨论群，感谢有你
