### ISSUE TITLE
macOS 11.6.4   无法设置开机启动，添加自定义 gif 图无反应

### ISSUE THREAD

**Issue by jijiangrui** [W-Mai/BuZhiYin#22]

**Comment by jijiangrui** [comment]
登录项已添加

**Comment by jijiangrui** [comment]
![1680162937547](https://user-images.githubusercontent.com/20493438/228768947-47c11b77-41c7-4fb0-ba74-08d62b37a849.jpg)

**Comment by nugurr86** [comment]
是下载的app store的最新版吗？
version: 2.1.1(14)

**Comment by W-Mai** [comment]
https://github.com/W-Mai/BuZhiYin/issues/10

**Comment by jijiangrui** [comment]
是的

**Comment by W-Mai** [comment]
> 是的

无法添加自定义，但是可以添加默认的吗？不能添加有什么提示吗？可以截图展示一下

**Comment by W-Mai** [comment]
方便的话可以添加群聊进一步沟通
QQ群：739654386

**Comment by jijiangrui** [comment]
ok

**Comment by W-Mai** [comment]
https://github.com/W-Mai/BuZhiYin/commit/49136c7cfe32eb412be023cdec6dcb483e1352b8

**Comment by W-Mai** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/24841247/231210760-0a70682c-90c1-49f6-ab2d-a9621795ebbe.png">

**Comment by W-Mai** [comment]
App Store已更新，请前往App Store更新或下载
<a href="https://apps.apple.com/app/apple-store/id6446803018?pt=126160538&ct=github&mt=8" target="_blank"> <img src="https://github.com/W-Mai/BuZhiYin/blob/main/Snapshot/app-store-badge.png?raw=true" alt="下载不只因" height="80"/> </a>
