### ISSUE TITLE
新的版本还没在App Store更新，请问有编译好的安装包吗 、？

### ISSUE THREAD

**Issue by AeronZhang** [W-Mai/BuZhiYin#25]
求教，或者可以介绍下怎么自行编译吗？

**Comment by W-Mai** [comment]
新版本已经在审核啦

如果想自行编译，可以直接把代码下载到本地，使用Xcode打开项目，修复依赖后编译即可，如果遇到什么问题再在此处反馈😁

**Comment by W-Mai** [comment]
App Store已经更新啦！
