### ISSUE TITLE
更新到最新版本后，默认小🐤们都没有了，💔

### ISSUE THREAD

**Issue by porum** [W-Mai/BuZhiYin#27]
![截屏2023-04-03 18 49 19](https://user-images.githubusercontent.com/48167317/229488773-35da806a-2b39-40a6-9b46-9637383ce069.png)

系统：macOS Monterey 12.6.2 (21G320)

**Comment by W-Mai** [comment]
你好，方便加群详细说明一下吗？
问题反馈&交流群：739654386

**Comment by W-Mai** [comment]
> +1

正在修复中

**Comment by W-Mai** [comment]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/24841247/229731603-523deb49-618c-44c0-bb87-a96f1e12cbbd.png">

已修复，正在等待审核

**Comment by W-Mai** [comment]
新版可临时在群文件中获取
