### ISSUE TITLE
CPU占用过高吗？20%

### ISSUE THREAD

**Issue by purespike** [W-Mai/BuZhiYin#28]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/26758630/233880219-9c2204c0-42a0-4c95-99ec-992918c9f0c5.png">

**Comment by W-Mai** [comment]
麻烦提供一下操作系统版本，以及当前的CPU占用率是否是在打开了设置界面
之前已经优化过一次占用率
https://github.com/W-Mai/BuZhiYin/pull/24

**Comment by purespike** [comment]
macOS 13.2 (22D49) 
确认了未打开设置界面
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/26758630/233895811-19a8eccd-d629-41cc-b079-4449c27df37b.png">

**Comment by W-Mai** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/24841247/233896696-79e9812f-6e36-4cf4-8486-5fdd90fb4866.png">
是否把该选项拉满了呢？以及是否为自定义gif，如果是自定义gif，图片过大可能会导致CPU占用率过高

**Comment by purespike** [comment]
也不是用的自带的猫猫
<img width="412" alt="image" src="https://user-images.githubusercontent.com/26758630/234149780-afa18450-cad6-446c-8532-b35c550868b8.png">

**Comment by W-Mai** [comment]
1. 尽量用小的gif
2. 不要让他持续运动太快
3. App Store保持最新版

除此之外其他方面的性能消耗问题我再排查一下，如果有进展会在下一个版本在App Store更新！

感谢支持！

如果方便的话，欢迎加入readme中的QQ群详细讨论，感谢🙏🏿

**Comment by purespike** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/26758630/234150722-61be77a7-f45e-487e-a8d2-3128f14eb96d.png">
<img width="2416" alt="image" src="https://user-images.githubusercontent.com/26758630/234150772-7d2f4cd8-0ca9-49c5-8f99-db44e994642a.png">
主线程占用的 那应该是gif本身动作吧

**Comment by W-Mai** [comment]
> <img width="1512" alt="image" src="https://user-images.githubusercontent.com/26758630/234150722-61be77a7-f45e-487e-a8d2-3128f14eb96d.png">
> 
> <img width="2416" alt="image" src="https://user-images.githubusercontent.com/26758630/234150772-7d2f4cd8-0ca9-49c5-8f99-db44e994642a.png">
> 
> 主线程占用的 那应该是gif本身动作吧

是这样的，设置页面每一个显示的icon都会解析gif，造成cpu占用率高，现在采取workaround方法是当设置窗体隐藏的时候，隐藏掉所有icon，从而降低使用率。

从你的profile数据来看，cpu从始至终没有下降的趋势，可能是没有触发以上机制。

你怎么看呢？

**Comment by W-Mai** [comment]
下一步优化措施是将gif的解析结果缩放并cache住，从而减少一定的占用(｡･ω･｡)

**Comment by purespike** [comment]
你说的隐藏窗体的时候，隐藏掉icon从而降低使用率这个在我这是生效的，我对比了主窗口开着和关闭时候的占用有浮动，特别是在我切换到「只因」的时候，这个动画比较简单，并且调低了「只因速」后，CPU降低到5%
所以应该是你这个默认的动画本身占用就高，我一开始选择的是「猫砸键盘」

**Comment by purespike** [comment]
不过我突然想到，你这个可能会死循环
当CPU占用高时->提高gif的播放速度->导致该应用占用CPU提高
          ^------------------------------------------v

**Comment by W-Mai** [comment]
> 你说的隐藏窗体的时候，隐藏掉icon从而降低使用率这个在我这是生效的，我对比了主窗口开着和关闭时候的占用有浮动，特别是在我切换到「只因」的时候，这个动画比较简单，并且调低了「只因速」后，CPU降低到5%
> 
> 所以应该是你这个默认的动画本身占用就高，我一开始选择的是「猫砸键盘」

了解，感谢宝贵意见，我来优化下ʕ •ᴥ•ʔ

**Comment by W-Mai** [comment]
> 不过我突然想到，你这个可能会死循环
> 
> 当CPU占用高时->提高gif的播放速度->导致该应用占用CPU提高
> 
>           ^------------------------------------------v

会有这样，

1. 这个系统在这个状态下是开环的，所有一个“正比只因速”的选项，该选项是反向控制，起到闭环作用
2. gif的播放速度有个最大的上限，防止超速太多

**Comment by purespike** [comment]
嗯嗯 好的

**Comment by purespike** [comment]
我刚看了下代码（我不懂swift系列开发哈）
我发现fps影响最大，我默认是80fps，我调成10fps（0.1）CPU占用下降显著
我觉得在这个statusBar这个地方，应该没有这么高fps的需求，或者可以开放给用户自己设定
<img width="717" alt="image" src="https://user-images.githubusercontent.com/26758630/234165835-5d4b9de0-b6ba-4a3e-9ca7-68d4bbf2d150.png">

**Comment by W-Mai** [comment]
> 我刚看了下代码（我不懂swift系列开发哈）
> 
> 我发现fps影响最大，我默认是80fps，我调成10fps（0.1）CPU占用下降显著
> 
> 我觉得在这个statusBar这个地方，应该没有这么高fps的需求，或者可以开放给用户自己设定
> 
> <img width="717" alt="image" src="https://user-images.githubusercontent.com/26758630/234165835-5d4b9de0-b6ba-4a3e-9ca7-68d4bbf2d150.png">
> 
> 

感谢您的建议，后续版本会往这方面考虑🤔️

**Comment by W-Mai** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/24841247/236094749-0d6e3250-54db-4d1c-9432-1c3adb7613cc.png">

App Store性能优化已更新，帮忙验证一下谢谢🙏

**Comment by purespike** [comment]
只因速调到65%左右，关闭设置界面，cpu占用在2%左右，性能提升明显🎉

**Comment by W-Mai** [comment]
感谢！
